### ISSUE TITLE
current master/v4.7.0 version crashes in windows

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#570]
Seems to be related to the new currencies that were added.

Investigating the issue

**Comment by mxaddict** [comment]
I've treid debugging the wallet with `gdb`

But all I get is this:
```
Program received signal SIGSEGV, Segmentation fault.
0x012b7958 in _HB_OPEN_Load_ScriptList ()
(gdb) warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

bt
#0  0x012b7958 in _HB_OPEN_Load_ScriptList ()
#1  0x03490798 in ?? ()
#2  0x014209cd in __dbc_close_pp ()
#3  0x00000000 in ?? ()
```

**Comment by mxaddict** [comment]
@aguycalled @proletesseract you guys have any ideas on how to debug this on windows? I'm not used to debugging on windows, maybe you have a suggestion.

**Comment by aguycalled** [comment]
No idea, been years I don't smell a windows

**Comment by mxaddict** [comment]
> No idea, been years I don't smell a windows

I've still been using it, but only for gaming :smile:

**Comment by mxaddict** [comment]
I'm lost trying to debug :rofl:

**Comment by mxaddict** [comment]
I think I found it:
```
Thread 1 "navcoin-qt" received signal SIGFPE, Arithmetic exception.
0x00005555557a7235 in NavCoinUnits::format (unit=7, nIn=@0x555559328538: 7600000000, fPlus=false, separators=NavCoinUnits::separatorAlways) at qt/navcoinunits.cpp:296
296	    quotient = n_abs / coin;
(gdb) bt
#0  0x00005555557a7235 in NavCoinUnits::format (unit=7, nIn=@0x555559328538: 7600000000, fPlus=false, separators=NavCoinUnits::separatorAlways) at qt/navcoinunits.cpp:296
#1  0x00005555557a76e3 in NavCoinUnits::formatWithUnit (unit=7, amount=@0x555559328538: 7600000000, plussign=false, separators=NavCoinUnits::separatorAlways) at qt/navcoinunits.cpp:336
#2  0x0000555555a5ee57 in OverviewPage::setBalance (this=0x5555593284f0, balance=@0x555559328538: 7600000000, unconfirmedBalance=@0x555559328540: 0, stakingBalance=@0x555559328548: 514000000000, 
    immatureBalance=@0x555559328558: 514000000000, watchOnlyBalance=@0x555559328568: 0, watchUnconfBalance=@0x555559328570: 0, watchImmatureBalance=@0x555559328578: 0, coldStakingBalance=@0x555559328550: 0)
    at qt/overviewpage.cpp:188
#3  0x0000555555a5fad7 in OverviewPage::updateDisplayUnit (this=0x5555593284f0) at qt/overviewpage.cpp:308
#4  0x0000555555a21dd1 in OverviewPage::qt_static_metacall (_o=0x5555593284f0, _c=QMetaObject::InvokeMetaMethod, _id=16, _a=0x7fffffffc300) at qt/moc_overviewpage.cpp:182
#5  0x000055555678f651 in QMetaObject::activate(QObject*, int, int, void**) ()
#6  0x0000555555a217e5 in OptionsModel::displayUnitChanged (this=0x5555584c6170, _t1=7) at qt/moc_optionsmodel.cpp:150
#7  0x00005555558023aa in OptionsModel::setDisplayUnit (this=0x5555584c6170, value=...) at qt/optionsmodel.cpp:401
#8  0x0000555555763c70 in NavCoinGUI::comboBoxChanged (this=0x555558669390, index=5) at qt/navcoingui.cpp:1739
#9  0x0000555555a1e0d5 in NavCoinGUI::qt_static_metacall (_o=0x555558669390, _c=QMetaObject::InvokeMetaMethod, _id=33, _a=0x7fffffffc5a0) at qt/moc_navcoingui.cpp:290
#10 0x000055555678f651 in QMetaObject::activate(QObject*, int, int, void**) ()
#11 0x000055555699301e in QComboBoxPrivate::_q_emitCurrentIndexChanged(QModelIndex const&) ()
#12 0x000055555699470c in QComboBoxPrivate::setCurrentIndex(QModelIndex const&) ()
#13 0x00005555569948a1 in QComboBoxPrivate::_q_itemSelected(QModelIndex const&) ()
#14 0x000055555699a7dd in QComboBox::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#15 0x000055555678f651 in QMetaObject::activate(QObject*, int, int, void**) ()
#16 0x0000555556991969 in QComboBoxPrivateContainer::eventFilter(QObject*, QEvent*) ()
#17 0x000055555675b94c in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) [clone .part.60] ()
#18 0x00005555568e4945 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
#19 0x00005555568ec527 in QApplication::notify(QObject*, QEvent*) ()
#20 0x000055555675d098 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
#21 0x00005555568eb442 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
#22 0x0000555556934235 in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
#23 0x0000555556936b6a in QWidgetWindow::event(QEvent*) ()
#24 0x00005555568e496c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
#25 0x00005555568ebfaf in QApplication::notify(QObject*, QEvent*) ()
#26 0x000055555675d098 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
#27 0x000055555626808b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
#28 0x0000555556269be5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
#29 0x000055555623ce64 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#30 0x000055555622d816 in QUnixEventDispatcherQPA::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#31 0x000055555675ae7f in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#32 0x0000555556764aa8 in QCoreApplication::exec() ()
#33 0x000055555572c214 in main (argc=3, argv=0x7fffffffd6d8) at qt/navcoin.cpp:656
```

**Comment by mxaddict** [comment]
Looks like the cause is this:

1. Open wallet
2. Wallet loads
3. Wallet tries to load Price data
4. Price data is not loaded for some reason(Could be a slow connection, and the API request does not get the prices)
5. You select a currency that does not have price data
6. Wallet crashes

I'll make a patch now and PR to master

**Comment by mxaddict** [comment]
```cpp
    quotient = n_abs / coin;
```

Looks like this line is causing a division by 0 cause the factor is zero
