### ISSUE TITLE
Wallet Crash when importing a wallet.dat with an existing blockchain

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#581]
Wallet crashes when I copy an old `wallet.dat` file into `datadir`

Crashes on rescan

Backtrace:
```
navcoin-qt: sync.cpp:125: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&): Assertion `onlyMaybeDeadlock' failed.

Thread 7 "QThread" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe6ffd700 (LWP 9416)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff780d855 in __GI_abort () at abort.c:79
#2  0x00007ffff780d729 in __assert_fail_base (fmt=0x7ffff79a0588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555576b0ec6 "onlyMaybeDeadlock", file=0x5555576b0ebd "sync.cpp", 
    line=125, function=<optimized out>) at assert.c:92
#3  0x00007ffff781d986 in __GI___assert_fail (assertion=0x5555576b0ec6 "onlyMaybeDeadlock", file=0x5555576b0ebd "sync.cpp", line=125, 
    function=0x5555576b0e58 "void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&)") at assert.c:101
#4  0x0000555555e00bea in potential_deadlock_detected (mismatch={...}, s1=std::vector of length 2, capacity 2 = {...}, s2=std::vector of length 2, capacity 2 = {...}) at sync.cpp:125
#5  0x0000555555e00fa8 in push_lock (c=0x7fff27c246f8, locklocation=..., fTry=false) at sync.cpp:150
#6  0x0000555555e0110c in EnterCritical (pszName=0x5555576ce012 "cs_wallet", pszFile=0x5555576ce321 "wallet/wallet.cpp", nLine=1926, cs=0x7fff27c246f8, fTry=false) at sync.cpp:162
#7  0x000055555578a9aa in CMutexLock<CCriticalSection>::Enter (this=0x7fffe6ff7ac0, pszName=0x5555576ce012 "cs_wallet", pszFile=0x5555576ce321 "wallet/wallet.cpp", nLine=1926)
    at ./sync.h:120
#8  0x0000555555788207 in CMutexLock<CCriticalSection>::CMutexLock (this=0x7fffe6ff7ac0, mutexIn=..., pszName=0x5555576ce012 "cs_wallet", pszFile=0x5555576ce321 "wallet/wallet.cpp", 
    nLine=1926, fTry=false) at ./sync.h:146
#9  0x0000555555e82d8a in CWallet::ScanForWalletTransactions (this=0x7fff27c24520, pindexStart=0x7fffafc65710, fUpdate=true) at wallet/wallet.cpp:1926
#10 0x0000555555e93eca in CWallet::InitLoadWallet () at wallet/wallet.cpp:4045
#11 0x0000555555b89fba in AppInit2 (threadGroup=..., scheduler=...) at init.cpp:1733
#12 0x00005555557408cc in NavCoinCore::initialize (this=0x555558ebe460) at qt/navcoin.cpp:257
#13 0x000055555573fcb0 in NavCoinCore::qt_static_metacall (_o=0x555558ebe460, _c=QMetaObject::InvokeMetaMethod, _id=3, _a=0x5555591c1f40) at qt/navcoin.moc:92
#14 0x00005555567af24a in QObject::event(QEvent*) ()
#15 0x0000555556902c86 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
#16 0x000055555690c458 in QApplication::notify(QObject*, QEvent*) ()
#17 0x000055555677e9ca in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
#18 0x0000555556781b7c in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
#19 0x00005555567d60e7 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#20 0x000055555677d2b6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#21 0x000055555660b6c3 in QThread::run() ()
#22 0x000055555660d88b in QThreadPrivate::start(void*) ()
#23 0x00007ffff7f8e75a in start_thread (arg=<optimized out>) at pthread_create.c:486
#24 0x00007ffff79099f3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

DEBUG LOG:
```
2019-08-06 21:07:11 init message: Rescanning...
2019-08-06 21:07:11 Rescanning last 15522 blocks (from block 3350538)...
2019-08-06 21:07:11 POTENTIAL DEADLOCK DETECTED
2019-08-06 21:07:11 Previous lock order was:
2019-08-06 21:07:11  (1) cs_main  wallet/wallet.cpp:1926
2019-08-06 21:07:11  (2) cs_wallet  wallet/wallet.cpp:1926
2019-08-06 21:07:11 Current lock order is:
2019-08-06 21:07:11  (2) pwallet->cs_wallet  wallet/walletdb.cpp:633
2019-08-06 21:07:11  (1) cs_main  wallet/wallet.cpp:1483
```

**Comment by mxaddict** [comment]
Found the issue, created a PR #582
