### ISSUE TITLE
QT Wallet crashes on linux system that can't handle system notifications

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#914]
Getting this backtrace on GDB
```
0x00005555558bd134 in Notificator::notify(Notificator::Class, QString const&, QString const&, QIcon const&, int) ()
(gdb) bt
#0  0x00005555558bd134 in Notificator::notify(Notificator::Class, QString const&, QString const&, QIcon const&, int) ()
#1  0x0000555555857ed2 in NavcoinGUI::message (this=0x555558b07590, title=..., message=..., style=0, ret=0x0) at qt/navcoingui.cpp:1675
#2  0x000055555585866d in NavcoinGUI::incomingTransaction (this=0x555558b07590, date=..., unit=0, amount=@0x7fffffffd570: 5980000000000000, type=..., address=..., label=...) at qt/navcoingui.cpp:1735
#3  0x0000555555c1b0c4 in NavcoinGUI::qt_static_metacall (_o=0x555558b07590, _c=QMetaObject::InvokeMetaMethod, _id=11, _a=0x7fffffffd4c0) at qt/moc_navcoingui.cpp:296
#4  0x0000555556cfd85d in QMetaObject::activate(QObject*, int, int, void**) ()
#5  0x0000555555c4bca3 in WalletView::incomingTransaction (this=0x555559799110, _t1=..., _t2=0, _t3=@0x7fffffffd570: 5980000000000000, _t4=..., _t5=..., _t6=...) at qt/moc_walletview.cpp:409
#6  0x0000555555b993c5 in WalletView::processNewTransaction (this=0x555559799110, parent=..., start=0) at qt/walletview.cpp:242
#7  0x0000555555c4b119 in WalletView::qt_static_metacall (_o=0x555559799110, _c=QMetaObject::InvokeMetaMethod, _id=20, _a=0x7fffffffd7e0) at qt/moc_walletview.cpp:257
#8  0x0000555556cfd85d in QMetaObject::activate(QObject*, int, int, void**) ()
#9  0x0000555556c7ab10 in QAbstractItemModel::endInsertRows() ()
#10 0x0000555555da85e1 in TransactionTablePriv::updateWallet (this=0x555558b3be20, hash=..., status=0, showTransaction=true) at qt/transactiontablemodel.cpp:150
#11 0x0000555555d9c7af in TransactionTableModel::updateTransaction (this=0x555559798580, hash=..., status=0, showTransaction=true) at qt/transactiontablemodel.cpp:274
#12 0x0000555555e1d30b in TransactionTableModel::qt_static_metacall (_o=0x555559798580, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffe8003fa0) at qt/moc_transactiontablemodel.cpp:94
#13 0x0000555556cfe37a in QObject::event(QEvent*) ()
#14 0x0000555556de31c6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
#15 0x0000555556dec998 in QApplication::notify(QObject*, QEvent*) ()
#16 0x0000555556ccdb1a in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
#17 0x0000555556cd0ccc in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
#18 0x0000555556d24e87 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#19 0x00005555567e0a81 in QUnixEventDispatcherQPA::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
#20 0x0000555556ccc406 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
#21 0x0000555556cd4dba in QCoreApplication::exec() ()
#22 0x00005555557a7f8f in main (argc=3, argv=0x7fffffffe298) at qt/navcoin.cpp:702
```

**Comment by mxaddict** [comment]
This should now be fixed in latest master
